export const Animations = [
    {
        atlas: 'character',
        key: 'idle-down',
        frameRate: 4,
        prefix: 'idle-down/idle-down',
        start: 0,
        end: 0,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'idle-right',
        frameRate: 4,
        prefix: 'idle-right/idle-right',
        start: 0,
        end: 0,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'idle-left',
        frameRate: 4,
        prefix: 'idle-left/idle-left',
        start: 0,
        end: 0,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'idle-up',
        frameRate: 4,
        prefix: 'idle-up/idle-up',
        start: 0,
        end: 0,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'walk-down',
        frameRate: 4,
        prefix: 'walk-down/character-down',
        start: 0,
        end: 3,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'walk-right',
        frameRate: 4,
        prefix: 'walk-right/character-right',
        start: 0,
        end: 3,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'walk-left',
        frameRate: 4,
        prefix: 'walk-left/character-left',
        start: 0,
        end: 3,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'walk-up',
        frameRate: 4,
        prefix: 'walk-up/character-up',
        start: 0,
        end: 3,
        zeroPad: 2,
        repeat: -1,
    },
];
