export const Bat = [
    {
        atlas: 'bat',
        key: 'bat-idle-down',
        frameRate: 8,
        prefix: 'bat/idle-down/bat',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'bat',
        key: 'bat-atk-down',
        frameRate: 8,
        prefix: 'bat/atk-down/bat',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'bat',
        key: 'bat-walk-down',
        frameRate: 8,
        prefix: 'bat/walk-down/bat',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'bat',
        key: 'bat-idle-right',
        frameRate: 8,
        prefix: 'bat/idle-right/bat',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'bat',
        key: 'bat-atk-right',
        frameRate: 8,
        prefix: 'bat/atk-right/bat',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'bat',
        key: 'bat-walk-right',
        frameRate: 8,
        prefix: 'bat/walk-right/bat',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: -1,
    },
];
