import { Bat } from './enemies/bat';
import { Rat } from './enemies/rat';

export const Animations = [
    ...Bat,
    ...Rat,
    {
        atlas: 'character',
        key: 'idle-down',
        frameRate: 4,
        prefix: 'idle-down/idle-down',
        start: 0,
        end: 0,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'idle-right',
        frameRate: 4,
        prefix: 'idle-right/idle-right',
        start: 0,
        end: 0,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'idle-left',
        frameRate: 4,
        prefix: 'idle-left/idle-left',
        start: 0,
        end: 0,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'idle-up',
        frameRate: 4,
        prefix: 'idle-up/idle-up',
        start: 0,
        end: 0,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'walk-down',
        frameRate: 4,
        prefix: 'walk-down/character-down',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'walk-right',
        frameRate: 4,
        prefix: 'walk-right/character-right',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'walk-left',
        frameRate: 4,
        prefix: 'walk-left/character-left',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'walk-up',
        frameRate: 4,
        prefix: 'walk-up/character-up',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: -1,
    },
    {
        atlas: 'character',
        key: 'atk-up',
        frameRate: 8,
        prefix: 'atk-up/atk-up',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: 0,
    },
    {
        atlas: 'character',
        key: 'atk-right',
        frameRate: 8,
        prefix: 'atk-right/atk-right',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: 0,
    },
    {
        atlas: 'character',
        key: 'atk-down',
        frameRate: 10,
        prefix: 'atk-down/atk-down',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: 0,
    },
    {
        atlas: 'character',
        key: 'atk-left',
        frameRate: 8,
        prefix: 'atk-left/atk-left',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: 0,
    },

    // Slash atack animation
    {
        atlas: 'slash',
        key: 'slash',
        frameRate: 16,
        prefix: 'slash/slash',
        start: 0,
        end: 3,
        zeroPad: 2,
        repeat: 0,
    },

    // Chat iteraction box.
    {
        atlas: 'chat_bubble_animation',
        key: 'chat_bubble_animation',
        frameRate: 3,
        prefix: 'chat_box_',
        start: 0,
        end: 4,
        zeroPad: 2,
        repeat: -1,
    },
];
