export default {
	id: 1,
	chat: [
		{
			leftPortraitName: '',
			leftName: 'Game Master',
			left: true,
			message:
				'Welcome to the Luminus RPG, a PhaserJS template for creating Action RPG Games. This is a Work in Progress project, so expect to find Bugs. If you find any, please contact me on the Phaser Discord server @SkyAlpha. I hope you enjoy the experience. Thx for playing.',
			rightPortraitName: '',
			rightName: '',
			right: false,
		},
		{
			leftPortraitName: 'lucius_portrait_beard',
			leftName: 'Lucius',
			left: true,
			message:
				"Oh!!! I see, so this is just a demonstration of what the Luminus RPG Template is capable of. Let's try it out!!",
			rightPortraitName: '',
			rightName: '',
			right: false,
		},
		{
			leftPortraitName: 'lucius_portrait_beard',
			leftName: 'Lucius',
			left: false,
			message: 'Hey!!',
			rightPortraitName: 'lucius_portrait_beardless',
			rightName: '?????',
			right: true,
		},
		{
			leftPortraitName: 'lucius_portrait_beard',
			leftName: 'Lucius',
			left: true,
			message: 'What!? Who are you?!',
			rightPortraitName: 'lucius_portrait_beardless',
			rightName: 'Beardless Lucius',
			right: false,
		},
		{
			leftPortraitName: 'lucius_portrait_beard',
			leftName: 'Lucius',
			left: false,
			message:
				"I'm you, but a couple years from now. Now you listen, I don't have much time! Beware to explore every single inch of this world, because here you will find The One who will show you the path to the biggest treasure you will ever have.",
			rightPortraitName: 'lucius_portrait_beardless',
			rightName: 'Future Lucius',
			right: true,
		},
		{
			leftPortraitName: 'lucius_portrait_beard',
			leftName: 'Lucius',
			left: true,
			leftExit: false,
			message: 'Nooo!!! Wait!! I still have a lot of questions to make!!',
			rightPortraitName: 'lucius_portrait_beardless',
			rightName: 'Beardless Lucius',
			right: false,
			rightExit: true,
		},
		{
			leftPortraitName: 'lucius_portrait_beard',
			leftName: 'Lucius',
			left: true,
			leftExit: false,
			message: '.....',
			rightPortraitName: '',
			rightName: '',
			right: false,
			rightExit: false,
		},
	],
};
